### PR TITLE
upload crypto tools

### PR DESCRIPTION
**Pull request by tianhao-srcn**
command line tools for password encrypt and decrypt
Win10: wincrypt.exe
Linux: secret-tool

### CODE REVIEW

**Review by wb0716 — COMMENTED** [review]
Good

**Review by tang-yuchao — COMMENTED** [review]
good codes

**Review by yan11meng — COMMENTED** [review]
good

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by xujiangang-git — COMMENTED** [review]
have checked

**Pull request merged**
